use alliDB;

insert into alliDB.person
	(person_name,person_surname,address,birth,gender,biography,death)
values
	('Edith','Ivanov', 'Moscow Pobeda', '1932-10-27', 'male','zjSQLhyXpYGXujsHQWnHSMqujGPBhXuFDDKySshcxBSkyJmmGFTARXrOFaZmgXnmmQNIZywznMKyQBFBDueNVGSQhNaoqCchftwFOUxxXllXNjyCWILXSVHRjmRXsVchUWScSeFxjYmQCjoOf',null),
	('Deborah','Ivanova', 'Moscow Pobeda', '1933-11-25', 'female','DkAsinUSrgMBowbwiSuSjUKmULPKqrsJFagRfZiAHaTveoROIKQGIHbwYdcmQNinSGLOEUmuajmzTWHlCEFvGAYczzzvTtsghodFhHaqCLRShcIIZUIVREDAXKjYDBxqLluadApBoYSpeRorD','2006-10-14'), 
	('Brenda','Ivanova', 'Moscow Pobeda', '1952-10-16', 'female','ROVewFCcrBMlVxPVHqkKLqTUESKDHUeABMMmQBoZthtMhRUPfJhKCMwHpMIJMVYkrFPJGlLwtPMzviVKdBtBsoKgXWDqFcoLblVLFSxfllfrqkcOHwRmuBwNuWYwoXmcJzdcxpumlltuCmXqU',null), 
	('Ivan','Ivanov', 'Moscow Pobeda', '1955-10-19', 'male','MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY',null), 
	('Craig','Ivanov', 'Moscow Pobeda', '1957-12-28', 'male','arCAitZtcEJVigIDRemMYyRcxZvBSpOHXqoDAynBpTcWhlIulUmTcjPeAMtvxwWbbSvXKnctalXDmrJEwiZEGoWhedHpbePQxqHmWfAtDItHqozdWcRJooCcSOfbeRATPQxmyQbFDsrYqYkTX',null),
    
    ('Alice','Petrova', 'Moscow Soviet', '1939-07-19', 'female','ynbuRYSuJVKnwLSOrQrvjRqIljQHMwUyggcXJyVkbKTnuNZszjHtuHnRkkWMtWyhThuJnvynNCuWnhPtJTFBWbPFXrFhSjjZBTHDvCmYcUXeVuOvwgNuPAmROIXnEtWpDsqEKEszicASCavtr','2006-02-22'), 
	('James','Petrov', 'Moscow October', '1938-04-18', 'male','iNVKktJvdcFaKkOSjvFtziVGOWFbYrtAcdGDvgJCkbwvtGQgiXDzexyCaWFytzJYfSoNUfnLzAYjqnsPigvCpHOjZaEpKCEwsbIyKKWfHlNVRAzrdaWeDUOSdDoZwixJPKaKgCtEmMJIAjAJR','2006-07-10'), 
	('Michael','Petrov', 'Moscow October', '1938-09-20', 'male','vYVkyUyvMTxvOXnGwscURBhFlflpvnuTUsVySHdctSoxdIJYwkxGQhvqqdfXPLZJHfMPuGVXRoHpmwWtjuYaTOcMqZloncUUYjEvhkmrwNBgMjqjRpERRlDsuYrgrmvcBolUhnqPQJnSSeZOK','2006-06-21'), 
	('Amanda','Petrova', 'Moscow Soviet', '1935-09-24', 'male','XTMcQQlLkgZtwWOHcCNcXihFjuiMPZSeeSaqRLwnTVyBXwjzxBOXAZWcUVpDHjTLaXZmfNUdshXyslnYhqxhoQSbXLkGRgQigChbmkBzPAwyCZAsXenmrNgvGLrtqAJDzepGjFLFtPEfqxdJs','2006-02-21'), 
	('Elizabeth','Petrova', 'Moscow October', '1936-09-27', 'male','dqHqofbqffNCnXdUtuRJEocOndYfSGZXwQlHvZNODVMSDaxcOQHDPABNXEByglrlHTrDLCnjipeoRaMVlLHbbUEgibGOeSckOHuBBotGrzVMSNpiMZytquHlCZYvWfqGXhygcqUDOPhUtxdNZ','2006-02-26'),
	
    ('Estelle','Smith', 'Moscow Pobeda', '1937-12-20', 'female','AtZdVNXAjhRcPimRXGkPLsWwyjzOVPJsCLjjvRVqErmfrHVtPJIdJgsRhUJBGjvfkgvuQRuVaisaJFEJEsdTqQpZnpGnbdXyVaeEJjABBzrEmwdpUWNzngxIFLYKjLXKMsfwOVjrEeLnkKeLt','2006-11-28'), 
	('Joe','Stephenson', 'Moscow October', '1936-10-17', 'male','yBANHTpzoJISGJFcmJtKqHdbSBmgoqVybAbTIYdxrlxawWYIXCZDqTaOGafFwMBjvkJdnzcXHxWuEFDPcUcpLxTqMIBFaPoYvmbHQopjDpQpZQNmxnDBVMpUwlZqhXsaGeLQHogDNZSjXZTMP','2006-12-27'), 
	('Ida','Czajkowski', 'Moscow October', '1930-10-27', 'female','TPzGpDQRqbMEpWyVwFgiLWvXFdrCKQLdkxikXtedZtlOAqZiHssVkIrtOJeUCyFBxaTZNkkOBWKKvCuNWstgblFGVQgeIabkIRnAxTXgIdcEgbEYGnaFIHGGsAOzxTWyqxsykSsLbaMhspMSU','2006-12-12'), 
	('Marty','Wolfe', 'Moscow October', '1930-12-25', 'male','LeagiySKJCzZoqzmGDlfdKNqkVoyrHQfLNrmAhaPIfKiedhmqIBXRoAMDfgCrykaCYiHWMyzNFunFitcFtSFHoLsKkhYcBVffiMbFtzHNDhXmpSWAnrTpjZNDxElNRDomFBpkoCDJyIGXxECK','2006-12-16'), 
	('Patricia','Robinson', 'Moscow Soviet', '1939-10-27', 'female','MJtkVUgAOBNvagOYrXxSDWrpOfykqHeeoRBlpEHpjhnEpSSwVuKQsDDAxKLcARtwMEeGzEzmcMXTSWpiKhBAMJPGUbGWBvrIkMJLnpSHeDaAWEGLELhjYgUXBFdSbEjuhlVkRKngJinCgVlee','2006-12-19'),
	
	('Mary','Tutor', 'Moscow Soviet', '1935-07-10', 'male','lsBEvZyZcagSrRqLZZGjPCiKfVUJZNFVxioJqVBYjQLcVElkWgHqFqGhaTrklEtruFDyWvozHssQqQFGfUCAsFdbcKsNdhdCCqAbjSeROTsWzeQAbnvZqDeJnYGWAfTcYFwHuJEYijLpctami','2004-02-23'), 
	('Rosie','Krouse', 'Moscow Pobeda', '1939-03-26', 'male','vKQsMsLjAnXeiOwDZwstcpXSimFIjkRvBQULrTzFCLfyFrfhhCeaUCmXBIyUrryQSAJZJiOgnxwmyoCzajawJOufnguXpfigFbcElDbngXGwBBwwjasGiaxJnRmMxuKUmrBqLpMlfQTWzqHaQ','2001-05-21'), 
	('Barbara','Crochet', 'Moscow Pobeda', '1939-03-27', 'male','KAwotabzDFbXYaVcnirYVZUraDSPSTeBOxGAfCEEumjmndmcdoQfmXkzAlPHDBRqTwrktNOprZgtPBkeWfxtjUfLPAcWZAVXzjKmLaqjOUeFWlGmSQuvNdvQmXUHqPjTSblRxrmkoCoPZFyZW','2001-01-14'), 
	('Sybil','Jordan', 'Moscow Soviet', '1932-08-20', 'male','tMBRNSjIxOvvenQmnVThotkqokkocZDKvAsOFmVPRHbcXCdwevnysxyGgOHHoCfBkpgTtMLXqrzUxtcgXglIPYMRmyLpcnkySVjLGqRwihgdLuUDhoSYrUBgLIYtotOYqKGBCJcaLkHWcWlPI','2002-05-13'), 
	('Elmer','Cornish', 'Moscow October', '1930-07-12', 'male','hkWUIkIgtZVenGrTQwGamxDHyjGYRgdKYyvbvzIGvMdQfvtoGwOmFLeEVSJPkihEiFfbMnvpgnePHqBFYsOccnxNhSkyiDDuGcSCOboFtrDNQWsNphwKkGkCBHfEFnEGLuLMeBXljtzzvryrB','2007-08-25'), 
	('Rose','Smith', 'Moscow October', '1934-08-20', 'male','dmJBWrpTtHMuOmYQptofjqeuSFfmdGcsdAxrtAplNXzKwvLZGcGLdIDkoDqrehRmuzhgjrBhQiVoflBRpAtHBeXyOrPJnXanAkdGasDBucsdRPHVhhdpfbuKSWOnusHhRhVHtyTuGIaZRKJXu','2001-01-27'), 
	('Aaron','Cropp', 'Moscow Pobeda', '1934-06-19', 'male','yJJrtFVaxBjUfPQBuUaJibCXnwFxOoSZyBikEQHiHmnPKYYAbihKuFiaCrxNYKGNkUgRyVlVSAHjDldUZkcELcqJrHvaijUhZGIMnWTMMyRhpwLXzlnhTjRhqYIMSuufFyOSizxEFAVgnxyeT','2002-08-18'), 
	('Chris','Cheek', 'Moscow Soviet', '1930-07-21', 'male','ewrSdsrbVPquKERmEgqJQiXxSZfqTjMBGWDPhNqdIWmTarFFJBGGCsgeMEBFiQbemODGxQwNjQnEvLziSDcVIMxuXBNeTUJrSObsJZyzhlpUEcAOFqyTcpRkfMgxSOXGaVWRnftygcAwOketW','2001-06-24'), 
	('Sheldon','Cooper', 'Moscow Soviet', '1930-05-15', 'male','UcANDyUciqVKuGQSbWEjiTUPtDXugwbGJsDRlwEPCHNBxFneTjHoPgqgtIdXyDwcFmwUvBmwdfTSwdAYuJseaKoLLSCtWXcuaOcOiiZVumjFCasVltYWLjQUcwuVatKNgyDfAPyMFewgpNevZ','2007-04-22'), 
	('Frances','Jones', 'Moscow Pobeda', '1930-02-16', 'male','yTpYPzFVnMYdrzgNUuEbxIGhMBmRxwxJOrczaMbKdXMmAOEXmEOkyPYdsFViVTKlAlhSwnVZouKKFzqDscKPwotfghyCvdYkVDPaSZroYiTAwMKuSCGzauQBqydhPApteWPYEaAffabumBkMV','2004-04-20'), 
	('Estela','Steen', 'Moscow Soviet', '1938-02-28', 'male','JOwNeoHuTHEthtzAAXspMvWuAGdPOCMJjYuImcrOVdyPfXlEBjhWdauUJvjuWiJIvOJBqZayeSLfuCdYUpniFWWaSZiFpvItabNUkSpKtOmyAZgJWHaRKdVZkeWFHeWeCtgWhBRZYQcZMIKOM','2002-03-16'), 
	('Wendy','Karel', 'Moscow Pobeda', '1939-03-16', 'male','CNYXrHuXFYQEGzYJeAvypPNgSlSZRHtqAkzgoCVPkalJTNwQGwqZiVsnHkexevhQEbbWBRceWjGiHtClupUvrJUhoouUwbnYqBAEVWTehuqiTtFVBhNxGtnlcNNURIJYhkMMPeMlMOuMRkKgn','2009-03-18'), 
	('John','Row', 'Moscow Soviet', '1930-07-25', 'male','knJuApLyciYsaXGgnZzPeHSHPJefnTZRJUhrwKtGUxlMgNHtFRmHhrWryBAjPYcJBksyMwPVmcdGgblYfBoAaVxsPZolScbePInwpePFDYFdOHVCRqVwMFQAWLebLiUUxGdTjlcjovyOECQBO','2006-01-25'), 
	('Ramon','Larose', 'Moscow October', '1936-05-16', 'male','fHubijvXJOTtOdlxjIrCZzxtUNVjNDJSSTOpZGIyVRNeFxkRuOwZUycDzUHmAzygUCGCpzPYcuffRfjfcBdHjEVaXplAaEinIesLbsQkpzzgfmhqmdbLLxkazKdSsakdeGawBOLWfRojJUfxT','2001-01-27'), 
	('James','Hull', 'Moscow Soviet', '1931-09-27', 'male','NivxFOqcakNgVwlzOLJkuaSKymoQdpewoKtdeUuVFBluEeFciRWAeXzyzcrhEgwIpgYjmUnzGtzxtmMEWwKCPeZZHHanBsrfLpMbSehsxzTTksOAnfYkTMLjmFVggMdqPeryinwUMQkttNBIF','2001-03-25'), 
	('Brandon','Zimmerman', 'Moscow Pobeda', '1932-03-12', 'male','XzdSNzGVryXjWfitYYpEpGnHiYnORHtcLiIvPMpDAUTSrMgepUiIVgRrwOQAMBOyLWiVTIZnnoOJxkcYFZfqtqryrBGUFvktOmHbvafQhNAJLyWIpmVsQVshYLHUpShvQKCIECmyGymlhYLOZ','2001-08-23'), 
	('Karl','Mattingly', 'Moscow Pobeda', '1937-06-21', 'male','XjsdyZZnSqhsdMWRQBlzWLDOoppXMKxdGWATSgAEUDHJwiilTjixwOnOLIcxaUciAyXrIBWgeFCUvLqtqIlewrlPtooefEbuSzWqnqbJDRVROnkeUpmebOLCMJPVWcLOyFyLyjGVKvSZGbeCo','2003-02-16'), 
	('Shari','Fish', 'Moscow Soviet', '1935-02-21', 'male','MbinBONXRMygsbJylpNSTDioIJnTivcrzokKycreOjpFfdIQNKXgTwYULjbNNPHfbjkEzGJOGneYUHGDxAMLpHQXzgKNyTluLuyrkqllXbhWvmpoPJmqMHiMQelYXhJUPDYlfnUweXRQmkIgz','2002-07-25'), 
	('John','Amparan', 'Moscow Pobeda', '1936-01-18', 'male','LfusLCsAMFLdrVMRcasuIcmqthSznqVfRUnxltKolVGOGlZOCmSSWQZwYGldkoRxEFlBTAwyAObqVTUZkTJEqixXRuJEFvDLeLKUUwhRhEyqOwMMmKxOwrUNHxvxmqKPfOtMbhmnEckXNEqVp','2005-04-14'), 
	('William','Mcmillan', 'Moscow Soviet', '1935-02-19', 'male','CTPQxrFEZDLxRrQJppHPusSbWEDkbHdCzKRRTKCMXqHBDaTyBYCeLvDXHoZujNsAlsGzLpQdiheHMwArnOQslxbgrtGOwxOqzRhZuyVgSTXAUJHsSZrdrQeJGDOxzsDXCZtRgPyJohPGZLrgz','2009-07-20'), 
	('Guadalupe','Groeneweg', 'Moscow October', '1931-08-10', 'male','JYBBOobaUEGDkfNSTyVZgiBZjFvsYhBQMzeSkEAWekUKOvzdtaHFZzBBzfjmuYdiXgSfIcvTHENAwobNFpICdgjyPjsfNfwisMiTdVUJsuYNNfGAmZfcRTbByQWWLZgTQfCtENHyqyodwKqon','2004-06-20'), 
	('Daniel','Jenkins', 'Moscow Pobeda', '1934-07-24', 'male','lqcbfNqgaXkZEpgEPdKRzdglGWravkZyyrKvuGbrLKMPiTvxsGeKaOlZwJeRJTddqefcrDCSvFimAkDJoMcRgGmQnrYCJIKgcBqezyEOywSaMGhNJuarbQcOAocNkUnUEFVynKQHgUzTlmvOo','2009-04-20'), 
	('Scott','Levine', 'Moscow Soviet', '1930-04-17', 'male','RXFFOuUPGYgXawLmIBGiaOoQDKFOeZHRyVTIwkIEyKkjRmFGgjBYqLYFDSsUjNIOWgkQFRYearJWycWeVchRmRnJKqNJLufoKThvnKwaaofDJbxvWCGmPzDUnRpfsbNUBIjrUKVSwLnkkRQMH','2003-05-13'), 
	('David','Griffith', 'Moscow Pobeda', '1934-04-14', 'male','CeKLEZgMPlBVdoCAEQcfNhaUWZDysKDfkYBuHCfHyeyxjLuQxZLPbNtACbDYwLrWpWEPNdeXSFodmIkUPynBgpOVlpHtOqssAlHCKBsLLGDSaATMFGxQQyiAlZqhkZKOQZlszLAmBqtdOoHWe','2009-09-11'), 
	('Tracey','Roten', 'Moscow October', '1934-09-11', 'male','KfcWZQjYFeHDcWcxKKemvVpANwpkgqHKCEtvLJyQjCOWDwkwIHpTRRBLCWhfJtXqkcQIYvQsxulFDdtYTpyZvRMAOFOXYpCYOBUZdWJSzKZODHBHxNMVbrpsDNfomPYcxDbcOymLLaksDQdWc','2001-06-26'), 
	('June','Moore', 'Moscow Pobeda', '1930-09-28', 'male','hHJxKJCWLuKCtOoppwNMhFxFXGpOBedgPwinqrvPpAZizbOcrISSOpFAmMXtorihEXMGZHleqgROybugmfRSvoBKzXRVJXYzGakbLrUSmtLvVjIZGmaRcGVmSxwEjojHsnIFgWoyYVlYubgDi','2008-01-20'), 
	('Daniel','Riggie', 'Moscow October', '1939-08-11', 'male','jrIcRdHnIuQzWQcnAfUWJQXvSUVdujJAhhsDKKGwnoRoMtPVBzTJVJuiwsOLprDaGMHvkpcZvwAirjezrsenTLAKPlkYcRjXlsMexEogDjUbCjkmXoMAGvhaHNEsFReodICELwrofTCcRBDwY','2008-08-10'), 
	('Robert','Alexander', 'Moscow Pobeda', '1932-09-19', 'male','lythUldoTsKZcbTQKhxzgvMVIWIiLAkNmVHzunlpzrrZpLtNjqPtZByJPPKUnYmZeqLWljdGoFnDkaIWlpcdRHYjahxqtkprpGXgapTvMwOfeVGIaHJLmjyrYyILbqkcjUwsGPQAzRpEYsXEf','2006-06-16'), 
	('Todd','Perry', 'Moscow Soviet', '1935-03-17', 'male','kEcwKapIWaCavioDayXshEpSMODpJHVJMUHOEzYePsTHiGJvcdGTFAnHhHJkMgDAacvYUWWnaowBPWidPlpnDPYXiKYvmjZKZoJCKdXFydlKJtblDpwwXkcgMbHsduecjKKvzxBhdZybmIwZN','2003-09-11'), 
	('Keely','Stamper', 'Moscow October', '1933-03-14', 'male','xzVGhsOJcDbzHHFJgROLrmyzLadAXbMlSKSgTuAqukWybVfVcNLohiVvEBGZAEnDfaOJwvHNnnYElXvbpQmHquzjWJLNHRdGsjjnFGNuWjqpPEvZnrSDORNShPPOQyeFTMcMFqDQCPBDSFtEz','2005-05-14'), 
	('Jennifer','Schleicher', 'Moscow Pobeda', '1930-04-27', 'male','DCcZhwceQzVygPOlTyjWnAZksZzcmXMJGnEBtRSJfpAHTYAaqhLuYCieejHkpsBIZiQbUoWkHXhjynzBOLtPADCONEQkMALzoKVeqJxgabUHEUHoAtGHBWTEPLJfNlsxqjQynmPjCGdMMUbkl','2002-04-14'), 
	('Joshua','Gillian', 'Moscow Soviet', '1936-09-24', 'male','SeqhGiEecNlPqpdUGmdfjBynCwbtURYfBMInrxZTzAFnoTxNSmdpqSwFMjchSbvMUYjnIjSbALUOKInaLuoWrqhDPqNYKqjVDuTnBfJImkqlFPvrFJpnycMPHIkodZJmzSAICokinladXPkWG','2004-02-22'), 
	('Barbara','Brandenburg', 'Moscow Pobeda', '1933-02-25', 'male','UvXfdZbEafJVPZUrhWwJGwmzuZkKuRuITZLRNcKccqdLuwGjkWVncAQdxxOwWkJXdHqVcLOpPJzbtQDddAcCwefNYbgYlAHLZpsxvchJwOOfiegcHNAAAyPAMigeZNlAAUGHcSUIbytdauWGf','2009-02-26'), 
	('Laura','Gugler', 'Moscow Soviet', '1936-09-27', 'male','MrNRqLYSkpVQAWDytkCFFfKNOuFODXUFdaadBxlPYPvQwZzDIUzoRDYcWgoGUUUTbUWNUxPAcMTEvqpdbGINxEAVBpdjxuhjDgzJOpbFnkNcmoeTGJdImRUccnDpvSbQseMReZZzEghVsZsfC','2003-06-17'), 
	('Cynthia','Carson', 'Moscow Pobeda', '1930-03-17', 'male','chlxtEsFzTgQCklhbfOHLrlpwCDLWRZnPdTIQcgOCIySUPczAXMulJjCzVCaZiwfvEasBSPNcErkWPZLeSrVHMVqPeCQsqiTWWYWRrpJYzXSaKQrWTDVlNokElcRqzChpsdeJoZYDcURIbVJO','2006-04-28'), 
	('Craig','Balducci', 'Moscow Pobeda', '1936-01-22', 'male','XdZDgLsQocapVPDChSxDwjkpRZPetRKwQHHkVtdMVSipqPZFKJdHrJeKryqaHxBPBYpJualWMjzBleuixNNOPcKfQkPrBZHSFmMEhthJeLHGNrrCgYVUaqhZjgbgmiMHUzgMnuecFqCduVeKA','2008-07-13'), 
	('Mary','Whitesides', 'Moscow Pobeda', '1934-02-17', 'male','mmNQexffeUGtyncZLtFBopigxkpQvZHrJOSWZfKgAophqfUmnEVaFgnTfvfEDyUKEUQEDNqZmlWCVecHfgOxFOtdoqvBGTFlIebScRgDopgjDuDVAUGvlsYAlsYquOwHkHWnFddvmfGWzavkH','2004-09-17'), 
	('Kellie','Cassell', 'Moscow Soviet', '1931-01-28', 'male','ZVPfaAAYTqYYOUafLoeMveBioExaKaVUfYposzefqZHjFxoLkaWCteIaWniSmNZsMPktFsgNMODZeZPXNSPxWkXxTyOewpZupUfMtWGBavsEsZZhirYNwCCiGqkUQxSKZXgeoDxIdeDfAgosr','2001-02-27'), 
	('Kristine','Sorell', 'Moscow October', '1939-02-22', 'male','BmxuwKoPtRsfsZCqhEJjBKkKuBKrUbTOmjllLEcZmwSPOsMMSGsSzKALJzltDUzamEdMzunouQsZZcyvrYMcyFrLtADoBkabSyppUnEnMPxuywLIcaoAlKXgVftWGoLbZXxhYtJFSKABIoJgx','2006-03-19'), 
	('Juanita','Johnson', 'Moscow October', '1937-05-22', 'male','mfXdSPZWOFHPVDNdpLnSpXywQcfAnAiQDSHAvqldJnwZBBTEFNCJRFPInuGPCrHPbzgqjZYVQpZrWAmaBVyevsEWzhcaOsGyMWmdMvGgnMvrmyVTGXSzDPPthJDZFkemlHABIwntSfgmMSIrY','2002-05-10'), 
	('Ronda','Heath', 'Moscow Soviet', '1934-08-16', 'male','VBiwmmpdLdoidZAQCRUtwagzudgwoMhlvGdSRliHEQAVgzKkuZkfaOFnzqdvNArSzAGIZyglwYwqNMQoGYCKhdSTyclXoldIygWQcDVAnBHvmromnWyvrjzxIUpuSXjKFBPWiutvoFJnUTMwX','2009-07-14'), 
	('Keri','Vasquez', 'Moscow Soviet', '1937-09-26', 'male','PWyjOTQmxUTBSfHJTyvYPAIQKpNfuHqWQeEPJMRmkHmOmntGrCOkqDlEvhkAYOgvkqTFatZXuxSdXSsDLSjaGCTSTzgYWAUuUgeoKCYhdwZlHDeDKDntANmGcOZEyMSHgEXtkdnxfWuWQymtq','2007-02-15'), 
	('Latoya','Palacios', 'Moscow Soviet', '1933-03-12', 'male','JTvwqiMwjYvMLodaZQyKxJMSuZlNDzBhngnQAQdPSIaGXdZbgWgHyzyuHpedJBuEMwyDVadHuqEVrmjAxasGvfpEmvbbEShJCayvldGhWFayTnpEwsQSSIRVAiajaBjZJKSYAOyNaCiJqhemy','2003-06-18'), 
	('James','Weaver', 'Moscow October', '1934-02-28', 'male','vgVjnLyZfeIhrqPYwbwGdRnWtwPOGJeTuLrWQrUETsHJPwDFGawzJpfSHECfjbvEZGSOVVubwrXbDrxORdOGhtiUckBNozHYkmCMWuIqYDmJvzMzrBlizFpqNvPXXUWMJTijBKWWUCLhBaZmY','2005-02-16'), 
	('Megan','Garcia', 'Moscow Pobeda', '1939-03-26', 'male','MNQnWeCAhlNDjBsHDsAXmMYJnboBNyKlHxhWwGAttfOOzxRdfPcffjXvaspNqoHeIovarQZEltAIRGkAQAOIxdKRzKVBMZNcHLaxDLcXtqsgpgaFEmEDZpTxtuPmBkPeqjfolmwjuwOirLsBZ','2002-07-11'), 
	('Herbert','Starr', 'Moscow October', '1936-03-12', 'male','CnFyZDUOMskmfMxBUTRnbYMXvVYgKgHDFHSZiWhouEaIGuNoawnwlGvLAkMGEhjnQAWjDcdWmoYFBmkEAxQuDeZAqIDUOyBRhuhhyjDKMTePgOijJeGrHbIvkOhgRfwVBGMjkIMWGdJnIOnRY','2001-02-21'), 
	('Suzette','Rodriguez', 'Moscow October', '1933-02-27', 'male','yymrcpzXYPWjnqaFqjEFXLmaGbFFjvplVlqkwjZUxXGHDqfEoJsljLUftxDRpGkuEJaEmxUcFCIypVIURZFKDOzYsFFAAbWoGMCOvsblxBgXGQFpWczfGrorSzYFRXahNWBeSCnrrKLrXCCFv','2005-07-27'), 
	('Neal','Gingerich', 'Moscow Soviet', '1930-08-21', 'male','mszAbogfnJchrnCWlAohcPPkdwDLLedvpMNWEsBYHItaoSDJgTizRACSQYhTZiYSYIhaOCZXBEWeUOpTPnEljhcAuWHyPlPMKRgnHKywPaDKFMhwdrXmVXKnOTLpcczJCzIgVIffYkawYAXrP','2007-09-25'), 
	('John','Garland', 'Moscow Pobeda', '1933-03-20', 'male','ynefYDJIGcMLpMddphAJusyvKOInIvawXyYNbugmjDSieZNjseEREEyhuXigSznxnfhQRLwPKqnshIInTOgRRvFwzaBVAmSdMhZjnZciJKknwSdynzUSWnxjMVkwNrkpmaNMjzhFfbHTBPHfi','2001-08-17'), 
	('Franklin','Lesnick', 'Moscow Soviet', '1930-07-22', 'male','AnvVkBFEhHbSCfMVCIurXrnSNWjxmhHVprYzlQipgNMcmGZCMaHCyaQqyenunzPDtqoctgMMEEuwtWHFmrUqgjonGIWYrbAtzuakVaEFVEeUtCconPEvHJzKIXRNbSRFHhecKBUzcirqqzLIM','2008-09-17')
;

insert into criminal_relative
	(criminal_id,relative_id,relation2criminal)
values
	(1,2, 'spouse'),
    (1,3, 'child'),
    (1,4, 'child'),
    (1,5, 'child'),
    
    (6,7, 'spouse'),
    (6,8, 'distant'),
    (6,9, 'distant'),
    (6,10, 'distant'),
    
    (7,6, 'spouse'),
    (7,8, 'distant'),
    (7,9, 'distant'),
    (7,10, 'distant'),
    
    (11,37, 'distant'),
    (12,45, 'sibling'),
    (13,26, 'spouse'),
    (14,25, 'spouse'),
    (15,40, 'spouse'),
    (16,54, 'spouse'),
    (17,54, 'distant'),
    (18,42, 'spouse'),
    (19,50, 'spouse'),
    (20,26, 'spouse'),
    (21,55, 'sibling'),
    (22,28, 'spouse'),
    (23,54, 'sibling'),
    (24,44, 'spouse'),
    (25,51, 'spouse'),
    (26,34, 'distant'),
    (27,61, 'spouse'),
    (28,37, 'distant'),
    (29,47, 'sibling'),
    (30,50, 'spouse'),
    (31,64, 'distant'),
    (32,49, 'sibling'),
    (33,35, 'sibling'),
    (34,36, 'sibling'),
    (35,42, 'distant'),
    (36,60, 'spouse'),
    (37,56, 'sibling'),
    (38,53, 'spouse'),
    (39,40, 'spouse'),
    (40,48, 'distant'),
    (41,49, 'sibling'),
    (42,51, 'distant'),
    (43,59, 'distant'),
    (44,57, 'sibling'),
    (45,46, 'spouse'),
    (46,49, 'spouse'),
    (47,49, 'spouse'),
    (48,62, 'distant'),
    (49,60, 'sibling'),
    (50,62, 'distant'),
    (51,61, 'sibling'),
    (52,57, 'distant'),
    (53,60, 'sibling'),
    (54,60, 'sibling'),
    (55,58, 'sibling'),
    (56,60, 'sibling'),
    (57,59, 'spouse'),
    (58,61, 'sibling'),
    (59,63, 'spouse'),
    (60,65, 'sibling'),
    (61,65, 'sibling'),
    (62,64, 'distant'),
    (63,64, 'distant'),
    (64,65, 'spouse')
;

insert into cases
	(person_id, article_id, start_date, end_date, authority, sentence_id, times)
values
	(1, 1, '1962-10-16', '1963-10-13', 'SMT', -1, 123),
    (2, 8, '1962-10-16', '1963-10-13', 'SMT', 6, 123),
    (6, 1, '1962-10-16', '1963-10-13', 'SMT', -1, 123),
    (7, 8, '1962-10-16', '1963-10-13', 'SMT', -1, 123),
    (8, 1, '1962-10-16', '1963-10-13', 'SMT', 3, 123),
    (9, 1, '1962-10-16', '1963-10-13', 'SMT', 5, 123),
    (10, 8, '1962-10-16', '1963-10-13', 'SMT', 5, 123),
    (11,3, '1960-09-22', '1965-04-27', 'MMM',1,0),
	(12,1, '1963-06-16', '1965-04-24', 'MMM',0,0),
	(13,9, '1960-09-10', '1965-08-23', 'SMT',4,0),
	(14,8, '1963-08-14', '1965-04-19', 'SMT',2,0),
	(15,4, '1960-05-27', '1965-06-11', 'SMT',-1,0),
	(16,9, '1960-01-16', '1964-04-11', 'MMM',2,0),
	(17,5, '1960-01-25', '1964-01-22', 'SNG',1,0),
	(18,2, '1960-08-18', '1965-07-27', 'SMT',6,0),
	(19,2, '1960-02-18', '1965-06-15', 'SMT',3,0),
	(20,3, '1962-03-22', '1965-06-12', 'SNG',6,0),
	(21,2, '1960-01-15', '1965-01-19', 'MMM',5,0),
	(22,4, '1962-05-24', '1964-07-25', 'SMT',3,0),
	(23,10, '1963-03-21', '1965-09-16', 'SMT',-1,0),
	(24,5, '1961-07-10', '1965-09-25', 'SNG',4,0),
	(25,5, '1960-04-28', '1964-09-21', 'SMT',1,0),
	(26,5, '1963-01-15', '1965-06-19', 'SNG',-1,0),
	(27,3, '1963-05-14', '1965-07-10', 'SNG',4,0),
	(28,5, '1960-02-23', '1965-09-22', 'MMM',5,0),
	(29,1, '1963-06-19', '1964-07-14', 'MMM',6,0),
	(30,7, '1961-08-20', '1965-04-12', 'MMM',5,0),
	(31,2, '1962-03-13', '1965-07-25', 'MMM',-1,0),
	(32,4, '1962-09-13', '1964-07-27', 'MMM',-1,0),
	(33,3, '1963-08-19', '1965-01-18', 'SNG',6,0),
	(34,5, '1961-02-11', '1964-02-18', 'SNG',3,0),
	(35,6, '1960-08-12', '1965-06-12', 'SMT',5,0),
	(36,5, '1962-09-26', '1964-09-26', 'SMT',3,0),
	(37,9, '1963-04-10', '1965-02-14', 'SNG',5,0),
	(38,7, '1960-08-20', '1965-09-27', 'SMT',4,0),
	(39,2, '1963-01-20', '1965-03-20', 'SNG',4,0),
	(40,6, '1962-06-26', '1965-03-20', 'MMM',1,0),
	(41,4, '1960-07-15', '1964-02-17', 'MMM',0,0),
	(42,4, '1960-09-18', '1964-07-18', 'SNG',5,0),
	(43,7, '1961-03-28', '1964-03-14', 'SNG',6,0),
	(44,1, '1961-07-15', '1964-07-28', 'MMM',3,0),
	(45,2, '1960-08-12', '1965-09-28', 'SMT',3,0),
	(46,10, '1963-09-15', '1965-02-16', 'SNG',1,0),
	(47,5, '1960-06-22', '1965-07-24', 'SMT',5,0),
	(48,6, '1962-07-23', '1965-06-10', 'SNG',0,0),
	(49,7, '1961-03-20', '1965-04-20', 'MMM',1,0),
	(50,2, '1962-01-25', '1964-03-25', 'SMT',5,0),
	(51,8, '1960-02-23', '1965-06-20', 'MMM',5,0),
	(52,8, '1963-09-22', '1965-02-23', 'SMT',1,0),
	(53,2, '1962-02-24', '1964-02-15', 'SNG',4,0),
	(54,9, '1963-09-19', '1964-09-11', 'SNG',5,0),
    
	(55,1, '1965-09-27', '1966-09-28', 'SMT',-1,0),
    (56,1, '1965-02-26', '1966-01-15', 'SNG',-1,0),
    (57,1, '1965-03-25', '1966-06-25', 'SMT',-1,0),
    (58,1, '1965-05-19', '1966-09-21', 'SNG',-1,0),
    (59,1, '1965-09-20', '1966-09-26', 'SMT',-1,0),
    (60,1, '1965-03-17', '1966-09-12', 'MMM',-1,0),
    (61,1, '1965-06-15', '1966-09-22', 'SNG',-1,0),
    (62,1, '1965-06-20', '1966-03-11', 'MMM',-1,0),
    (63,1, '1965-04-11', '1966-02-10', 'SMT',-1,0),
    (64,1, '1965-07-21', '1966-08-21', 'SNG',-1,0),
    (65,1, '1965-08-26', '1966-08-21', 'SMT',-1,0)
;



insert into case_info
	(info_description, case_id, info_content)
values
	('evidence1',1,'witness'),
    ('evidence2',6,'witness information'),
    ('evidence3',7,'witness information'),
	('evidence 100%', 10,'XqkFwGPxpNMaxzoidAvyxlXBGwYaqoIWowqLSVjZ'),
    ('evidence 100%', 11,'sgXCAVLBxfQTenHMYZkdGSzgWsYayIwlJclLbxsD'),
    ('evidence 100%', 12,'zTyNWWDLCNrpDHnPdPbsacomTbNYSOycjDCpFxGF'),
    ('evidence 100%', 13,'tVQVnYytiOXJHsmiZIwYhkthGETQPNMdnzeOTHtW'),
    ('evidence 100%', 14,'QdIpMiwxcAyxHLmSbyiXVcutoyAntwLvtwxYLYtY'),
    ('evidence 100%', 15,'CdTSZqRpHRyhJgRtOhdCMAoSzokhtLNRPWAwLCRU'),
    ('evidence 100%', 16,'UPEtLMWLDoPMbfhQVWoRTvShQhdiALLPUsOHLnHn'),
    ('evidence 100%', 17,'jWVpqzOGSHcJEkBNPCEViAiaCEsbDRDnfPrrxjGQ'),
    ('evidence 100%', 18,'zelFYwdQbfPxWgTPSJaMguufVwfYaFWaAdcVgPNN'),
    ('evidence 100%', 19,'AJxtPgVmXeLiaShYfPiZcSxcHukUTTOGSKgLdHSF'),
    ('evidence 100%', 20,'PLkbUXjElHzMHmsHyGDUSxQjwMMAUWvitWLCRRSj'),
    ('evidence 100%', 21,'jFfHGIbbEzuqoFqsTYWPAiFdayrtsabrweCBzPPx'),
    ('evidence 100%', 22,'zjoSAZzcCgkRiSLltXjABpwmkZnOZHftQmwbTrks'),
    ('evidence 100%', 23,'OtTtcfZWyvfXGNgNlYyHKKUJpzfbgaHNMocMYxft'),
    ('evidence 100%', 24,'xwYXEqhGjHLwdhRpLpmuFIxiEyRngyUYfiRZLdGd'),
    ('evidence 100%', 25,'zIFoINyJiURuVPdEkskCbbsuCpcMiVgGOKszTevC'),
    ('evidence 100%', 26,'ZosuMrXliVdTscRTBKKdQjGXNfmxLMfhhcuSaBbv'),
    ('evidence 100%', 27,'mEBuOFHOjjLNWPyJNPxSphRYaejUDDyZUBzlbmCK'),
    ('evidence 100%', 28,'xNWMTQvpYyTuiMILNmsokCJiaahKssvRjIeSihHS'),
    ('evidence 100%', 29,'CgSNTGpSPsaETfCfmfPHICDyaOazxmeQxRkMomLE'),
    ('evidence 100%', 30,'mUjvyplfJCLkFXPUNVjiNBXQAmXIojgqpoCwrrml'),
    ('evidence 100%', 31,'KBEWQaOOQKDhEtAbHcNNEMKDArOYYSmbIYNpHHTZ'),
    ('evidence 100%', 32,'qzUqhkiZJDOTDYSMzfVaxpHeaYaEJxmdDxelieBG'),
    ('evidence 100%', 33,'QsrfXAzkVJdAyPRqnTekSSXOwQivNPajxXlXHWhS'),
    ('evidence 100%', 34,'MuVhJFbsaPHlzHdkEvkfDGVEVsTxDOTnjoIwERDc'),
    ('evidence 100%', 35,'YGlmhFtkBlzmwsYNcgWPwhwEBwHmTVqsKhEUYpQQ'),
    ('evidence 100%', 36,'yJtxjTtrctgFeOkVwomHoNrkLApaFmkqNKgLiPJA'),
    ('evidence 100%', 37,'wdOSAEVxdUHcpgdwMwINjSHFLyGencNUVHzNPMiX'),
    ('evidence 100%', 38,'RxeFfptrUguUzixdOFCqGgOvRQdwcJJMFKQCdUyy'),
    ('evidence 100%', 39,'TuybxSKiQHGzsQvCwZyaCDSBObCssTwoyNPbHwof'),
    ('evidence 100%', 40,'mBrxVHsaOaEunHqrzXmrcpAOFXPYXeMZfSYTpEQb'),
    ('evidence 100%', 41,'OKMPKkaZrWicenxfvSGKfvHMKEKKASeXyyLPywQi'),
    ('evidence 100%', 42,'iVjksMCfhtNtcwAIHHAUKFZDFcLetSxnJkzCLags'),
    ('evidence 100%', 43,'cZuPEOMEYYUbtggpGGilozkcegXVFqCYlTZjdLRR'),
    ('evidence 100%', 44,'fcbUYqAAVFsOOjbEcoBMkqNJsrtCqlqKoEwMdPtv'),
    ('evidence 100%', 45,'svvCvxLQjkcnquMSlJlATmWlmZtnQWCCgNJfzKpQ'),
    ('evidence 100%', 46,'GlwKdwZZkenvHrTxAKLkKGupFyovGROQvWcpWEbi'),
    ('evidence 100%', 47,'XsOUbZJWNcPhgvwwNkfyslfYUAZUrJImXpmnzuRK'),
    ('evidence 100%', 48,'NrHukLkLmVJzjLdNXgntqfEQbvsYXVVNcaqPCrvJ'),
    ('evidence 100%', 49,'agCWPSNVcIMbekVvYXzjZsoxUmZoTUlKqQscZjwq'),
    ('evidence 100%', 50,'drGyFgOMPWOwajBHrngnLVydLHWKzWlravzVuQMt'),
    ('evidence 100%', 51,'hdisUgWUqhPQphiNbeMwGAKBMsyOwEjaRbQWAhQY'),
    ('evidence 100%', 52,'gbxTVxcOqhGMmGwEbTvTSLdZRxwYePKfixxFQscv'),
    ('evidence 100%', 53,'KNPodoOxbXqDnfMYxKMxbixHTVBVuIrfzmRpHgsa'),
    ('evidence 100%', 54,'mVvgYNtlPeRRlEKLoDTTRQBMMhUNhjnCxHvzJiqN'),
    ('evidence 100%', 55,'TtqsSOZfFNRzBigmlGZMhDdPGetdIXFnKcJoRNXG'),
    ('evidence 100%', 56,'PYGSFEwPAgWltTXbmAtzfiuxgMqMxyqsMEEJlVAN'),
    ('evidence 100%', 57,'yMJYudSrXewgPdmsJIcTVCAMiZTgWEauUefyUwcL'),
    ('evidence 100%', 58,'zAJQfxuslVGNZZxeyRyIZpPszdwSzyUMrvZMnLYQ'),
    ('evidence 100%', 59,'zhoIWofNmignQtfmbuvHOkjlKbBhloEfqhgIHWsv'),
    ('evidence 100%', 60,'BGePYQyrpVHwvZlRXuuUtCmwMoSdJVyCxarwanUN'),
    ('evidence 100%', 61,'AZGebSEKnHczvCsNNflRKnIvGgdWRlLsOaAuesWE'),
    ('evidence 100%', 10,'iidDAOEKsjInKwhEPIbsFlTcOESYRiryzruHiuNT'),
    ('evidence 100%', 11,'CpIuNEaPkEkLziJapboeErkNNUIydLwagWyXUGak'),
    ('evidence 100%', 12,'VcoOEqOXSHUOShlzwfPbFeVqgBIxGOHKLfHcKWDv'),
    ('evidence 100%', 13,'UjIARRSmPZQhEUjYjXUkuuSxiGbsQcurHWgalgKf'),
    ('evidence 100%', 14,'ACIXMZOvHsOspTpbxQOusMHdzkeKulGDZTfyupil'),
    ('evidence 100%', 15,'USLLAncrRVLFoxplZoOZhraPmOxgkITXOfUOdvZs'),
    ('evidence 100%', 16,'pDrJByGGPhEoSvBAVkOtSqaWKKLwSluuZJooUszB'),
    ('evidence 100%', 17,'qpymQWtnJgSEiqiXdOOJVUDvfSJvGVUmsQESxGvb'),
    ('evidence 100%', 18,'JIfksuVwwnuobURDVSGThBZnPtAwPyIpJMkBwQbO'),
    ('evidence 100%', 19,'CfqDWIJQTgSPVODvjqRRVPgPfDjpcqDqdbDfSyno'),
    ('evidence 100%', 20,'alTFmzhUCBokfZfdNPPkkihzHhaIGpmIUAKupgLj'),
    ('evidence 100%', 21,'lnaIPFSQVyIXMknjTOAhAujuPGLUFpVTOpwKmJaS'),
    ('evidence 100%', 22,'OlxJegfzHrHwEJejjGuoQGYaEoEhEPREpMofUzbs'),
    ('evidence 100%', 23,'ZKamsHXsCGImRzqbqiFHMQYhhqTskPVwWkSoBTAE'),
    ('evidence 100%', 24,'MrRHaePbBIKMKTHSetJvwmKmfgJqLprfnlHppmWc'),
    ('evidence 100%', 25,'ilHVxzheVIVhvvgHJxMVzGobwMfXHRvUIDTUeEAC'),
    ('evidence 100%', 26,'dXrUErpRQMYHOIEwJBtdbcopVOENuFGyymknKZSp'),
    ('evidence 100%', 27,'HFpHtbszNIZdPHZKWYORFKfizfwImkjaZcxUGIar'),
    ('evidence 100%', 28,'zdMMbbJQuvywIMejuWPhcEPPLhdgyGummuQRMTpM'),
    ('evidence 100%', 29,'VuxyPwdmacUQZjAbuCXkgOkmLzzdFbWdORMsEkmN'),
    ('evidence 100%', 30,'EMurUgZKgBrpNdwyvuIONbstKsmGDbKqaMYOEknx'),
    ('evidence 100%', 31,'uAfNeirTyBEkXxgzeTnKqJeHKMzBegSAFAfQjoqW'),
    ('evidence 100%', 32,'YiUoFqXOMbyJSXyKYFLDbfWcriKzXrdkRsgqvYTE'),
    ('evidence 100%', 33,'guUtWSnXbvVvfCuWktlXyRrtxSqTqYReAZluEivx'),
    ('evidence 100%', 34,'WXMWZjrCVwwDLJLbOYfLkohwlqDAFPcSfnNBmIBG'),
    ('evidence 100%', 35,'aukBtCXvefeKeDkqHPgMGFQvXXyWdMKJjpuofuQu'),
    ('evidence 100%', 36,'MKfMSIcCsfCSonTxenRtJHVRxUYeyHEwAWGePYQY'),
    ('evidence 100%', 37,'iqxNjZPQXsGOXNsCeggCjuPIBoSqUmeJPBtpeRam'),
    ('evidence 100%', 38,'HtdxHAqUuDfHnerxXXPyYzkZBNRUozOElnyinAdb'),
    ('evidence 100%', 39,'rsYyVFKiTDwxkacRZQkxgPqRqIFomYpJluapnEbh'),
    ('evidence 100%', 40,'UBQlkabOjHMIOLxHaVWvpsuJFOVamiIgozBGXNqo'),
    ('evidence 100%', 41,'daVYiPoXEZXXNayddTyCrQGPmjWUyeRSbxutBVuN'),
    ('evidence 100%', 42,'lFXXsAjiWoFdhGlIeWvoItnCAxGyRwFbVcPvFwer'),
    ('evidence 100%', 43,'fcYymxEslqyGkyKNhMWSkOmDBOIOQtGWJXAlHcdw'),
    ('evidence 100%', 44,'zQgWsCDjnQQmSbSiSGvvpMVjwPPEcTfTCaQCGgsC'),
    ('evidence 100%', 45,'vGyDvuMkEpMoLpWJTspVLLFeudwNNIZmMIQsJDjf'),
    ('evidence 100%', 46,'ISoGsWPWXUiVWZaHACVFbizITxzPqKmcxUzAGrtI'),
    ('evidence 100%', 47,'pYOXkJhjwdWUzEmtuqMDrSobSJjZwtvoArrsbHKd'),
    ('evidence 100%', 48,'HSbnVJjbvOJKehnEbSiBdBnSrkjSXaxPlnWTCxOw'),
    ('evidence 100%', 49,'xzboCxXvCXdwXWDAFZsnlPUYNkFxrCAoMotpJtGV'),
    ('evidence 100%', 50,'QtQJGUerrVhPYDpqUIsuvhGhetOoLbMqUFIQqFQz'),
    ('evidence 100%', 51,'oNKXmgCuskWgTwhCXvkcCmlTDCayVCAHkeqskolL'),
    ('evidence 100%', 52,'gwzBFHrrgjEnjfvEljaEbajhCgEsDFUuIbScbwvp'),
    ('evidence 100%', 53,'VxnwuEMKgqKnoPKKBnnlpRSuqmJmmDdIEooKLPlN'),
    ('evidence 100%', 54,'veVOnhTuZpIMztayovTMbwKhVoIWUiJeABfVyipx'),
    ('evidence 100%', 55,'eHrLJfHIGMsTFouNLUtldxkDTqxwHUNjlSArGPKS'),
    ('evidence 100%', 56,'PnOAkGBrmQzlwwBLUacvMHRXRjqlfXYABjQwzbRe'),
    ('evidence 100%', 57,'sqkHqPRDdxnXtqzPSuglLpaNtuQGYCZWEBZohQyI'),
    ('evidence 100%', 58,'WvKnbIIPSehTpFDxIjugkseYCQpbTyrTynRYTOxs'),
    ('evidence 100%', 59,'mucYMaXQNqObKEtyGhhfVSXenkbiTCGRpbRusLTk'),
    ('evidence 100%', 60,'TeavsJROvZoUgImnnOMbEBgXBUlEPiwdqiKbayvw'),
    ('evidence 100%', 61,'gGTgdqZZiLXTQFpWbHmBQMxDHPElySZnTQNSvDkR'),
    ('evidence 100%', 10,'yGXloqIDSbtsiLPobBgdKUIYrfFctEEzxqXUMzVC'),
    ('evidence 100%', 11,'qpfyfnmvribXjbxDJeVpsyvPpfVdJLYNAxVjHuBI'),
    ('evidence 100%', 12,'LhzuXLeYtkgkzFLUSiOavrElDuktDtpRsXPNOart'),
    ('evidence 100%', 13,'IXRGLeApqwXfFVAuTLzopxeyXmQhNYJvwLQSJiUe'),
    ('evidence 100%', 14,'RRSeQIrFUQcWdpobXzbvskChFjXCtlccDQZWpyWu'),
    ('evidence 100%', 15,'hRGVtdzOUtaWJlIipUcqUSVgJrpKXscMuRqiszOG'),
    ('evidence 100%', 16,'arnrqtbAoafWxRyBEoQHXlHTrCwdfaYuPAuYBXjU'),
    ('evidence 100%', 17,'gfWtVcmGGAjDQkLKQgEDNMyuERxnlihjbGRBYhpX'),
    ('evidence 100%', 18,'NlJPBWjXMCfdktksNUPHwKxWnTZVjMHZQXBIKJAJ'),
    ('evidence 100%', 19,'XIMONAEssQcvEXXAmALeIrUmGsUQUEjKhEMnWvnc'),
    ('evidence 100%', 20,'XPlmsgIEZayvmOUHRcEMsvRJRVGLZRWredEOopiS'),
    ('evidence 100%', 21,'cJqoMIXphyjpxMITmpeKBcaiQDLQNpAulzBVIjgr'),
    ('evidence 100%', 22,'VreKfFlkwUSgpqFxKZezedSiOALCUKzZiRsmUdSj'),
    ('evidence 100%', 23,'UKKjXGJafzqZbkEEjEFsjENjCltJggZvUZiFtjNT'),
    ('evidence 100%', 24,'IbkHXwiHIvlgtVXfEklSSRJWdFGOJaXoowPHbVSd'),
    ('evidence 100%', 25,'nSxaEOedulTJTvOOWyyKvFLilATkNlYRCEcufTUo'),
    ('evidence 100%', 26,'MKodECSynjEExynRXBWJvwKOVAPwYYiMmCgipuHS'),
    ('evidence 100%', 27,'cotBvXJqVPrDcgPXqhMjFzDhRkFivKjkjHFeXUBx'),
    ('evidence 100%', 28,'KuzZjkqVzXcwuaHpreCXZYpRcqubzAWyzLXXnZML'),
    ('evidence 100%', 29,'AmkaHnksrRDBhtJVEjBBwSReLMLpvlcYwTtzvavb'),
    ('evidence 100%', 30,'BHICQsMPgBIHdtsdsATZawTWrIBYgkQQGWIaxItS'),
    ('evidence 100%', 31,'YrnJYhiqdnLExfyDaTFpJIACoorYTCvlWTcuvmSN'),
    ('evidence 100%', 32,'jcHkgroxYZpYzJUHpfVWcfnfKnHQbqDMMyKaJEPJ'),
    ('evidence 100%', 33,'vPiGsqyJCRTZLOBsGOtBwzpEareoQfmoahTGKNgT'),
    ('evidence 100%', 34,'OVNEvZTkRnXLWZXqTJTdUTQJdGnnMBGeGuJvfOdJ'),
    ('evidence 100%', 35,'limPAymgEehgPJqnBdOzRnnKGFfAiEsaXTUBdBGG'),
    ('evidence 100%', 36,'UewLizbYzuwdQZEfDpbdehOJPuitjKvCAmXlHvkj'),
    ('evidence 100%', 37,'OPdhQKhBvcZZPksbxQbHwIhFzoDVLFztBlCMcfIS'),
    ('evidence 100%', 38,'gSbhHJMrGtRNyFHPvWdGpDEiQTuydveLVlTUaBYd'),
    ('evidence 100%', 39,'DJxwsEVwaHtPBqIHuFyTZmrVgFuLcfOexsbjpZcj'),
    ('evidence 100%', 40,'sIcdNTpJKzBMFPjfvDMUWjKDDqRoYytbNAQqifFo'),
    ('evidence 100%', 41,'VONrPKaWOuNflYzYFAbSYVgHKBVMkkqVmmXqgMsU'),
    ('evidence 100%', 42,'muqQjwXKlseVTlBymCweUVnYKoExfqQCvjEcLOct'),
    ('evidence 100%', 43,'MNTaoHdkVRvJFPpITReyxtyamDUWjWqdXvVczBHf'),
    ('evidence 100%', 44,'TwEzMGfEVZBfVifZIMliiPWTfrnSJIqlOPquyznt'),
    ('evidence 100%', 45,'haLEZIgYxxwknHnmDoTZmWUCrpOaerVgAgCRAusf'),
    ('evidence 100%', 46,'fymlhvpikfTdrZypTmHdMtRppKqeHNwUmogSdRrL'),
    ('evidence 100%', 47,'eQFaFOLQPTmSBLDaOdKmuooNXxOkSNvCcekRHVpB'),
    ('evidence 100%', 48,'uJPewHCnBZMiGaIrWBlKCUSrXoQJBOwkRRXWGpSu'),
    ('evidence 100%', 49,'FdtLYickRlHfheuWAdBSBOOQdFjYfQtrdeGrEsYX'),
    ('evidence 100%', 50,'nnSYkOpzoYDisrinpHEWpABFnetKgTeNTNWUpFvP'),
    ('evidence 100%', 51,'AmoQFSBoKNqRhiJelRONgmtuRSIFlUPhECMvgHgy'),
    ('evidence 100%', 52,'QLMRAlTEUJtztjuyRJsItZBQtfGfnsFkmVlyYecu'),
    ('evidence 100%', 53,'bQsIsZZOBwjHiGHWVjMBwcuTnLtwJMiDYvvBNhhG'),
    ('evidence 100%', 54,'PvNNUGyARkoPjeFdNaonghfwVbuCGTfHbfAXvcsC'),
    ('evidence 100%', 55,'RnmvzLEgxGGkeOxHrOkBRjvaTkbHqIuFZpruyKkk'),
    ('evidence 100%', 56,'jIlnUEOWGRkPdeoslFwNPSahUKtWMdWCGBTQzhnO'),
    ('evidence 100%', 57,'FljSmQlKLuWRkNNCphYmRmOxIoCXNNTKzBKtvcOS'),
    ('evidence 100%', 58,'knzAAxUfdwNQZtqNImCfvDvkjZsSnucJLseNqKVc'),
    ('evidence 100%', 59,'EslRHiGNvybUkrwarRDYfKCvJtKIYqaTahqRsOir'),
    ('evidence 100%', 60,'VOOzGxQXxwggjEPgPXDyqxgsfghWjXhBrQLJaAZN'),
    ('evidence 100%', 61,'KbDQiwjGSdCuHWLAjxTlGUYjcozIBYDtzgqnyFxb'),
    ('evidence 100%', 10,'eyQqtrEEnQsovKVRDtlIDrqdwfkAmVIpjStGqGgI'),
    ('evidence 100%', 11,'sdaIrTwsyUVySaykHogYrRElTUXXkllUNnBTNTGc'),
    ('evidence 100%', 12,'TNTuuafRdTNYdTPpIPQCyEcmrloWcpHTWOXEgcPm'),
    ('evidence 100%', 13,'DNdukTKRGTIWjjNsmeQbrCOSTQFUKglXcIJjQzTc'),
    ('evidence 100%', 14,'VKpQoJSEKJQfLFEPzZYXWQYznMoroyYssmvStKYq'),
    ('evidence 100%', 15,'XcuDAIdyvBYvEejviPQBSwGtcECaoxPVzWeIRAYU'),
    ('evidence 100%', 16,'fWnzbpGVaxAiYqBwWIrtfIJJLaCmACXTmQYiryue'),
    ('evidence 100%', 17,'rUHqWwzPsvRMLQhGgFQLmvleMCjuRZsYadvCrBAm'),
    ('evidence 100%', 18,'esVEzIAWSyUpwarDnmjAzjciihSxyOYCVJCnSOfZ'),
    ('evidence 100%', 19,'eCMuaBzStGNeFbmpMEFHTFPOHInrdxxjBELXbRhZ'),
    ('evidence 100%', 20,'VtighrHUEOwOMhoqpUTNRrknFuWEQHPSXBytmOcN'),
    ('evidence 100%', 21,'ctsZIRzFOQjJMyvSGknjBJfaEuCrSVWWGygqLIrt'),
    ('evidence 100%', 22,'qSzXCRClwTLVrdJbuaYIRuuNiSZzTJiJPYHqhDCd'),
    ('evidence 100%', 23,'afspQGgUBJiANmhxOzxFJoyGuVaUhqpXTZbaufgt'),
    ('evidence 100%', 24,'hUOIiXAXmbjnruqMdCUTvZDmVIcCjYZVtmWVhkah'),
    ('evidence 100%', 25,'bjzoEaHsxwFkTqrcwJOJFjevfAiwCrQOoQqpLQvZ'),
    ('evidence 100%', 26,'ScRsuxsPHKHgNzCVjJIDkMcnxqqgdeQQeYosZCfO'),
    ('evidence 100%', 27,'yRigJJnwJJMGmIEizjgmjPhiotWoUvHpMpZWqtAV'),
    ('evidence 100%', 28,'fpLwBvVfYtKkCaVVeOXDACsMirMrcqCGoMSkUXlJ'),
    ('evidence 100%', 29,'oexvTdcBhQbScWEmoJgvBRMizfgGkTCBwvGPgoSE'),
    ('evidence 100%', 30,'oEQzZzSxZabaYdeyVYqjknojdnSlsODfwtCeMpYb'),
    ('evidence 100%', 31,'AVsBqMJaQOpQYLtFHJvlHOtlvaLItqxrmZqEDTLH'),
    ('evidence 100%', 32,'glLhjVAHPuDjHHskdArsUugRTSIDZuJYlTkWDkVT'),
    ('evidence 100%', 33,'bJakNZNYQEpJecGfVqSiWhEHelBhZSdyIsFnQqmL'),
    ('evidence 100%', 34,'frCrNeInxurdaivWEkVldJOIxSaQIZXxjfQYqfAC'),
    ('evidence 100%', 35,'uGisWIVdksWcLQODYWdLECxflrcaIVohZxRkeXLi'),
    ('evidence 100%', 36,'XtYSZacqkQuIBiHpFqvLNSQwtvNyhIVGWPvGeSnn'),
    ('evidence 100%', 37,'LxqjUzjSGcYnBMHuJLkiMPTNHynajZzBQGYnpepM'),
    ('evidence 100%', 38,'BVqQKSTwUXgtoUKQVDQkNOrBSeOuleVoXxtcxVux'),
    ('evidence 100%', 39,'mzMlcYJqgozUYPnsMCFOtPiRdOnqWMvCLwGeLnUJ'),
    ('evidence 100%', 40,'TnETtrdHGywHBYjmZQZFcjlNUntgfswWeXVDxZoG'),
    ('evidence 100%', 41,'NXDkyGBUcLczFWUjsppqOCPFRGOhGYvPhexitumC'),
    ('evidence 100%', 42,'XFQopwHfPbZIRhoipzHELKspphxZCBWSmOdDRVUs'),
    ('evidence 100%', 43,'ezhMjAoVrNkKktmAkltAZmdHcsfygFGfNmcxXHWB'),
    ('evidence 100%', 44,'WQAkojxrzMidkFiafuORVYRAvzfDXhnTeMuaNZqy'),
    ('evidence 100%', 45,'hFYwXdPNMlQSMoeJGMhiAqNuQEwsAkiNMSqEujtn'),
    ('evidence 100%', 46,'mvRFYtnJBbutWIDAWLDlVeQAfrjDtoIKtVeLfCmZ'),
    ('evidence 100%', 47,'wtKAVgVIGZeMFuiDrGJDxgZeYAPddEAfNdgmpJNt'),
    ('evidence 100%', 48,'bdeizJXFpkEZPuhlEJIZRmRGOpdLDzAkWAJdeeBS')
;


call shoot_person(1, '1963-10-17');
call shoot_person(3, '1963-10-17');
call shoot_person(4, '1963-10-17');

call shoot_person(12, '1965-06-11');
call shoot_person(20, '1965-09-16');
call shoot_person(23, '1965-06-19');
call shoot_person(28, '1965-07-25');
call shoot_person(29, '1964-07-27');

call shoot_person(52,'1967-10-17');
call shoot_person(53,'1967-10-17');
call shoot_person(54,'1967-10-17');
call shoot_person(55,'1967-10-17');
call shoot_person(56,'1967-10-17');
call shoot_person(57,'1967-10-17');
call shoot_person(58,'1967-10-17');
call shoot_person(59,'1967-10-17');
call shoot_person(60,'1967-10-17');
call shoot_person(61,'1967-10-17');
call shoot_person(62,'1967-10-17');


call prisoner_arrival(1, 5, '1963-10-17');
call prisoner_arrival(2, 6, '1963-10-18');
call prisoner_arrival(3, 7, '1963-10-18');

call prisoner_transfer(1,4, 5, '1967-10-17');

call prisoner_release(4, 5, '1978-10-17');
call prisoner_release(2, 6, '1983-10-18');
call prisoner_release(3, 7, '1983-10-18');

insert into compromat
	(person_id,compromat_description, compromat_content)
values
	(54, 'iNihJPcPUgHgDkdAQbFQAgZBcNwgzFGRXSZnxVLq','mjJTKLtqvvQbvZgJUzfWaczBdgqVkrslAemoUCIJscgCQtYjTWOvjpeJCaSdwunpWRvpET'),
    (25, 'sTROVteQcgWLgkYbEHPgWaeGLEtapAtZEVqTzBAK','FtWXZNUhmcALjXEqNtNRGvwNPKRxiuJKeKVXUzXIWUkIgyMJLflmHWCiJKwASbeYulJLzQ'),
    (9, 'FklEvIHCwUngZNtAFENWmQbrraOZkfnZXrizRUbK','aLhxeQrdMbcMedoodJDkmNNZeLABUvcbYyrGBHEOnyOLmDSZQlGCAUueqaNYGTmCSmAWBy'),
    (17, 'vWBKPwVKLuchkDBrfeQdphsdwrDlPLUKxqTRUvfs','VCveNcOkXsoWQkjmiACFfIvNGKWzuuGygIeVyrvWGdomchsRgHvWZJpkcaRxwVngGGtbId'),
    (25, 'jawpkrOOIYHAzCTzbDlRtvlXrSizpRYfGZggzNpM','kwBlGNRaEpikroyReMrOXREbQLSheAAPioMyikXIJyChncIPpcePMQculuYCLylhtdNYZQ'),
    (6, 'KOFOCbChKAVUSAfWgXbBRdAEhwFYTmZPKluwgHEV','dtFaMkXlbJUhZbATEdESiDeZPtVayivnUHmRIvsVktTujoNczuWflCAiNuWnJJPZnqLjZG'),
    (29, 'njZCEiesgUHueePhDSCmxQZnuWFDFvyDXoCtOigt','nXtOqyckEwIIyTNNPFGvWtXITpSCZAfMjCcrgEYfhwzuDrNKUXrVHzDYmwuRMZEgjRWwPw'),
    (42, 'neAKODWszUlpWGnZjRTwOuUDTIcebrgsVoIXfFRc','RRVqeAVzJWybFzPUGbCpIhquMpvtYsSZuOpfpRYztjPjFtAGORFxMjuKnliWRlqzBKNTih'),
    (18, 'nOMYlTELvoifJvrHurgvULDGtodeqSMKZlSWJIgh','OqcpIVIHGfjvNqAXRdGtordTlsuPjSdEaoccNJpxmtzeJySFrZKJhgUqRGBoZymbWFpwto'),
    (65, 'KVxbffPxxrtffqGtsZCDHKmhRxyfzVHslkrkKLll','tojPYWcwSgFWFxrlVWhssrPLjRzszVdsCkUQdBdSxuAVdjLECDbmFkhzMcBImEMMRZICVw'),
    (3, 'VOtkFSYscQwlYCSAuxMarkBOoodQXXYIQmWTXhhW','yylzQMUhyEnaUTEZwIGHCMaoxPUutCCUznxOxdtrzBCpmkMsByNRZwamMuCgcolrsTCDQJ'),
    (40, 'WOOFQUdDjeTTIwFDlssulfwqYiPZEDdbHQrtnXvP','yCkCEvnufLLNBzFbTfDhhSxybriEagInppvVpMQoWmasgWMkJUDQFLjNxfTSOdYrklcIKa'),
    (51, 'IfUXEzoqGRIVQnctFiUWuhhucJfEphVJJUktpXrJ','ecDDjeVHbuMtbUlSHzfWQKNzdPgmWuikQJeARePoxQYsKkXwnuChsvXMsnGCWyVIIfxeya'),
    (4, 'QwUMUuEmcjcviSKLJuayEQFlBvIYDtjlsSHULWgx','tTNRsaVLZDMkSMgbxDKIcTaIVLSmvcgsggINrgBktEuGtDzjljbwCdwAjTXZcmhUxbXwDp'),
    (22, 'laxCKQtYKdHnzwqGbAFSPNFLbdNqmZFHNoQlHDWS','ksgTuHfKheMRgljVstBglMKxFccOfpKiyEaxksKkeSlQCBVpoYMnuQwcwgPAdcStJWbPDe'),
    (1, 'JQisYcvIxyWuWESFEDeHYlacqPVVNVNJlwUbVpBf','PiMOyVnnbpteOLczAKWwwrYoJEqJyHUGIThCWhzuNnARYatpHVfsJYyPdWaoFIfDAgSziw'),
    (16, 'cxKvtJtKJcAMEoiTkCOhXDnNNPxfJZYnFPJXzjkQ','rXRUvChcajfWvvguNpjRXAqkARfMmvmacAbqyRDLvlGAIxgvKyHXCNUxnnRbbNsTLSqTIl'),
    (60, 'aPiYLZRyveXNNhkykJcVPJsGwAXtuYXWjCnAkwbY','rkbgTNwZtZwYmWLLeCusMOtzEynbXDLTfguwjhzTSDDvlBmGkeRWDEweSxexMcjpwSvYtO'),
    (7, 'NqaDpwOYtYYftutifKlbkxZvobBqgOaeJAhABdPt','wzJeVSIqpPAZnXPzVJkkpuscXGCIDGklYtCrJnmeFKHjPDCeGwlxgrkCvSwehZRGtnhUiG'),
    (47, 'HtDRHIuEQQcOzQfdhILKkFLrDViNwmOcHjaduBFt','PjrILErXFWLrZmWLzAjneVlEkHxDFsKxRnuffKMjHlnpKHUfNGoSuCgmfmGwpcMFVNcOAW'),
    (41, 'JKzUqOpWVOwOeGzoESToUlpoMhonnigBIGadTyRQ','dKGbvBmggyozvWTAylrpAXKMyDdBkxTqFELoCIlKXkyowYXRyPBJpqpiTIrhaMxXgRDMkL'),
    (54, 'bCemIMyPESxIbTrPAaXSbctbshtKDfLAXtHRTwBc','zSlzkHdfUEbTasmlzZDZawQorlMOEgIISQcJEknIxkMpngXHYVJtpvrcCxfdfxFRYthQXP'),
    (4, 'CLTmJkxfXdXfPjqprACvSUuxqFxVIDbWZHqSTyIt','LutRHQYuIvKZfUhhtzLLczagQLlmBfxLvHabIBclFSpFQwVknoOlmwsEpUzIXcikvilorq'),
    (4, 'rVrKbsgUOwZqqjfaBBkEcZfEyfNDdltwUgNzIprI','kDSZgdRHzbJQylIQlZozZnITDnXBpseTahtAfIIFZYELFZjRyzyjgCgXFYlDHzGHLkVPzK'),
    (9, 'rXPlVzRkwEZxRsCaPQIqEPzGpAVXkVrLvKeQJXBy','bhwGujnUFSuYBoAGKnFjJcMkOkXthDpoJBFLfaOEzNkbjUaJkGJDHOoeeToUSCXVxkzWtS'),
    (39, 'TvlXweJlgLaCQWrxEBObTknxXOqqTrRhZqAtHGwD','ipXjNAsVcXfjhGeoeMfPXBeDqiVEqsZeSHLXjtcWmQcHPxYQDHfkFPGrSsocMZkgJcZyYB'),
    (41, 'jClPqDghANzRLtzqHvrSIEBOzztYPqVPVbPrCadS','PuOGYWWMTPhTCPDUdJjMhkrYqGxlTbTHZAyPjNsOrZOppgxRkAtpmrSTWnHcrQOJGdtXUN'),
    (49, 'LqjzHHPpCNrjLUVmeKgXNmqAYrVOUOcAHfYyhcpx','nnPQnSGqeNrzDNJJQOYgoyHdnurEwSgoEWYfUlTuutDvVIwpQjxTcpOnGKscQrylmLXQhR'),
    (65, 'vTCliRnYrDPDDWgcZhuzSwQgxVIOnsfQIJiEuViU','agAnwSiucHAmbWqiEWBMKDfplaHuWzDtkwphKdVPVhvfiRYdWfPhjGiyEuEBNthnhLrgqK'),
    (25, 'NhPrYxlzsQhRoLFvoOtSdfrIeTDkKtnekRDgJXCS','oLePdptcngGgoKxoyDPUvbOcyOKiXegHLdKEXOHpgqAVbhDQtyXPWjbGcRvicnQqDcELeG'),
    (7, 'PDmchAzRpflABAfnqTyhkAHjEIcVuRveZUMbhowt','lXDidKDGfNhvTjVKYxwKCnsQqigGiYFaJCBIvHGUYNKWWIfPBaeSPhGINWeEaxIUtvhGpQ'),
    (53, 'bSuickZIaezvRYOtkCAEpFPuGyZFUManymVrEjwK','VGKEPAkgnIFzrqhFVIhRzbAxwpwXbgTeDeMvMYZITQhwrtmgnkIMwobVFCSatvcBQaUpgt'),
    (28, 'MufUYKprJLuSEuFwgSBpJLNXZabZXjHNsgfXwqqQ','OXibATKnAbXsMAeDMPtmPFCkICFYyrmBQBrySFwGMBBzWIsVtyNEwyVvAiIytsJAsTwgNc'),
    (24, 'xelOROSCHnuBuOyLAuppFmIfVVOXyFPTQEZTqIvg','OiKaxRkAnrcAyyOhJQqXGhWZzqBdKdjzFMQFUpfvvbHtPFIWVlRzwRhHxxUBPfDlXymyqx'),
    (9, 'xcMePHFdRuwhAEOPBbqvDTkmiZrDBCpcDGnmkryT','RhVABMSzRHfKOlVWmpCcdTonDfEugvXPRuMeSDaOFMQpdVaMJYTSCiOznqWksKbBgRYBpm'),
    (62, 'oDAIZYSuGiSXgqLESutHcMObvrrQkwbOqwywBcsN','uPxCahwjNBxXYDyJKKyLCxjWQajYiNOZVBIBeNDQAxjvXuzvrAUxBXfMdtneNdBkGSBtdE'),
    (1, 'pqmejetiJmJiivbeyPlwuoOhgQgfhjdwVQdWMaWh','ZuPpEgRbgXzXmjnuisTEZrsDFQBmkPAIFtNnPJErlIVXIAwzmuxypajfmkNnjeRVjRxktS'),
    (22, 'eIzTaupAIktZaLPjANsLFzUotYbAAdlClEIVduoi','rxHQYYMqXNxioZamhQvWQFoqxczwKkCcVnKoDSfwutyIDqOeeMFeOwQbMXdhbcPIKwvAtI'),
    (27, 'OPaYtRgfNAfvWKYgwOPXxWPeiHKfecTbYRQfqEZB','OPklyrRJLWLAqkkgWlgVoSLcvGoemrEqKNRyaGRubpglcUjMOWafeCazDUYtYRiqcnPspZ'),
    (10, 'ilLoQXjgOGqfVlAtFrmszOSrtulQDOOZIOcxQqul','oZMWdPyFhDpLVbDBAGiJDLQjjpWRnntVkQwVYJWUAmwTdMdTaZlemBAGvYREEPooApjFFa'),
    (35, 'LsoocSvcRnFUiPATSMFKAnSKgVbQwdujZzwkBZim','ZJngaUvCkqWDGPOyJeAYtLmHlQWckpGmFrxavHZfHoVFeCRAgOYjFjifvKmmASbeMTQuRl'),
    (37, 'AeTADEINkHVaBdzTXsSCHdmGdnswQuKmRCoVwatT','uVbwbVdyVVgvbRwgxjqmqltMUiuiDvBcRbjTfuSnSUsPkFJgbTOsUXKXptggAlUbETalGT'),
    (20, 'OnMKzgjbglHFyutCrmaLfOAwMFxqUzaEysKyfDdl','BQSjuaywMNOtcurqbZtcYVlwXShYSFXTBpvOXpVdoCFWGNFZGtTHTbyCKhkrWchpgoWlXM'),
    (35, 'MRDIdlrwhjQEfsfTDxLmlySTkHvXKlilvichAGaU','kOegOcqzKkXsEhsaezLKfMvuJvxIbkttSLaPQLBowMbjeIsPISpGmYNOTXWbzDflaCMqCh'),
    (9, 'QZvYlAdMsBWRIqztHnApKsrwojlGXiVXdeqgpftA','EycIywEGnxidRLMAVgtbOtIsWfwbEAXGiHyCmfqsbeAGkEalNPBdfHiDHPYNJHYGSkAJnw'),
    (47, 'vEtLzCsBaYuaiROhLTjWvknStihrsHdyGDGOruHY','MDfyjOOVPoinuYiWBdCExYuGsJaIirilXpBIRXTEwodyPyzAvijOZgJBJtzMTERIksBpsA'),
    (19, 'MTiwadSNXUOudsQoYTEgjLPYIFrKlwbCYpzRnDwI','opyxfPcOQXRSGkhrTULGrcceEsAPrYRpkSUdBWxWYUXnBbnfPkHVsmMJxMaRMsgnceASlw'),
    (59, 'XAHMQnvRwTtVFLQXvCSCOrNFrcqvzrnWWWwRGxOC','lRNeSRvEktFgKWmXxxABYmtdDHLxeyXXFiAoVUIBBiHFjZsAyeRnmSfExYPYrCsXQZIqDO'),
    (50, 'xFXrcTyzSsJahAOTKnzHVSqDSOeglGNXbnowZico','YUScyNEnGtGrnnQKebjGFgSTdmzWoYOSadDOGOhyLRkEjhYGeqWNaWUluyIIYLMPnvaqrV'),
    (36, 'DDQCarqndilvJcGhHkjeowOIRkQUOSjCeUeCwfjt','JnMqPACdvXanWYLQmwYIKOCWjhVozbhemTzlujpvelggZFutHhkeIduGrvdxrQAlDSYTdr'),
    (6, 'OCtfaFkTFpiBOLwFAaXOlTVtMWJduWUVwmLwtdaQ','FZDqTyHbwTqqsKvinrjQkXomqUyReJDOmTZuWuaJeDlFZiOAoskxVhBZOvRvlmRZxmiQhh'),
    (43, 'XJbGSnGYJKklgSUifRDSUrZmoErgCXYNYLngBOFb','uUIkkjxckpfPgBzwIqgkuWnmmFsQKFrHvSgmOPycgfVGrkcFuVlfflyvhEqccZgdkLiugy'),
    (29, 'URDCjtDsfhiRicixgRTFRdcvBFJxyQEJDsPGsiQT','aWEAZFSGwVNJIOGnJCraSntUnHnqDayMIlkomafRmsArJhrhJnZtQtLgytEvFbdrrWniLF'),
    (15, 'bJNIEqRjEieHkcVFZteuoxVmACltNNiExRMqVOGd','HeoLfhGUhdvFpmumponkTRqAnzkcyMBoUxzsGADhHpAEWurVWNUKunlEZnBMiHKsSjAZQL'),
    (33, 'pyHansGBMPYYfjVGcrOGWEERMDZNmFeucVdnjqIA','bWzdoaOJwUGRtbukjnFMQbGCQfvVhxegCqlQWjfnhkpWcVAahacWEjSYfAPpAvAeEAXJzC'),
    (19, 'wSzdfdAyKykSWSSxpwWyTadknCXpCshdERqMyncR','ZqFdzxpbXJFyVRUGkJlUGUwadUAYGtrqcRrYuOBKtjMzYgvxKYYFMwAoYRLHBIYEaJbAAl'),
    (39, 'jUWJqyrtMgDcxKLeJgjhyTbXgISbgIdGbHxhmqqY','AAywBHxgucDZOUoIhupZepvPMllUcAxVIlbwKhGhghiYaxtyMyvQQylQOoxMAHSgdKUWnu'),
    (32, 'UjoszphdIHnVitMQDYMvEtXMfXJkEwsjJkBzUOlW','OUWwFXkYVruxApxHCCcngmHiHCXuwlhFPpJPNSyBtoYejYFfqPmPgGflMvBeDUQTBqhZoX'),
    (39, 'fTiyEbdQBcPpvFJowAnsRUHruOIdktXSgRRhLEvZ','idEFsOxEssztPqvtaptjRNlktzXFGYudCCtAHxMYWgoRqgmOWosAqxOcuZzMucgqAuthQN'),
    (36, 'RnWKXUYdhntLbwPxnkYdgImMGNKQHMEZMQhtYAWt','WIlmuTtFRfJRKRJYhISVGcTuxkTVHtCxcUiLSmWjugcYmTslVUmSPtTygMPyhGboNxdlhP')
;

insert into afterlife
	(person_id,case_id, address,  occupation, afterlife_start_date, biography)
values
    (2, 1, 'Novosibirsk', 'nurse', '1963-10-18', 'MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY'),
    (3, 1, 'Novosibirsk', null, '1963-10-18', 'MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY'),
    (4, 1, 'Novosibirsk', null, '1963-10-18', 'MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY'),
    (5, 1, 'Novosibirsk', null, '1963-10-18', 'MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY'),
    (8, 5, 'Tomsk', 'nurse', '1983-10-18', 'MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY'),
    (9, 6, 'Tomsk', null, '1983-10-18', 'MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY'),
    (10, 7, 'Tomsk', null, '1983-10-18', 'MsaWRBjPnCFNVkRmYLmexnhjsvrDhrVQHqBeRDKbFAEjfMXSsxUeacXJyNLInTsLXjcWwZqzTGGaZgUhcXeWMuDFnqWMOKBzilzECZPsTgyEFiWoEUkeZyAEmwMpfQvsIkKIljhpwdNsNYQvY')
;



